### ISSUE TITLE
can't run this project in my pc. showing errors.

### ISSUE THREAD

**Issue by MdAkdas** [Manisha-Bayya/simple-django-project#2]

**Comment by ManishaBayya** [comment]
@MdAkdas Can you paste the screenshots of those errors here.

**Comment by MdAkdas** [comment]
![Screenshot from 2020-03-09 23-50-34](https://user-images.githubusercontent.com/43089126/76244921-0432a880-6261-11ea-9074-cc18542aa578.png)

**Comment by MdAkdas** [comment]
![Screenshot from 2020-03-09 23-50-40](https://user-images.githubusercontent.com/43089126/76244948-101e6a80-6261-11ea-91a6-8cc8c701b28a.png)

**Comment by MdAkdas** [comment]
Version-
Python 3.6.9
Django 1.11.17

**Comment by MdAkdas** [comment]
hey.
it's showing this error.

File "/home/akdas/.local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 206, in get_connection_params
    kwargs['port'] = int(settings_dict['PORT'])
ValueError: invalid literal for int() with base 10: 'mysql-port>'


any idea??

**Comment by ManishaBayya** [comment]
I think you have given wrong port number for mysql. Can you paste your databases section from settings?

**Comment by MdAkdas** [comment]
yea. I've given the wrong port number. :)

**Comment by ManishaBayya** [comment]
It is working now?

**Comment by MdAkdas** [comment]
yea. but not showing the search results.

**Comment by MdAkdas** [comment]
![Screenshot from 2020-03-18 20-06-17](https://user-images.githubusercontent.com/43089126/76972889-34f79980-6955-11ea-8cc5-ae26d9729361.png)

**Comment by MdAkdas** [comment]
![Screenshot from 2020-03-18 20-07-00](https://user-images.githubusercontent.com/43089126/76972914-404ac500-6955-11ea-8f27-9f5251fa5bd5.png)

but database is showing in django admin.

**Comment by ManishaBayya** [comment]
Did you run `python manage.py rebuild_index`?

**Comment by MdAkdas** [comment]
now it's running. Thank you so much. :)

**Comment by ManishaBayya** [comment]
If you don't mind, can I know for what purpose you are using this project?

**Comment by MdAkdas** [comment]
I have to build a project using MySQL as back-end in my college. I was searching for the project ideas and then in got this.Teacher will not accept this project as they have prohibited use of any framework. Since i was learning Django, i thought it will be helpful for me.
